from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse, JsonResponse
from rest_framework import routers
from . import views

# Register the ProductViewSet with the router to automatically generate CRUD endpoints
router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='product')

# Custom endpoint for a simple "hello world" response
def hello_world(request):
    # Get query parameters with default values
    name = request.GET.get("name", "world") 
    age = request.GET.get("age", "unknown")
    city = request.GET.get("city", "unknown location") 

    # Validate and convert age to an integer (if provided)
    if age != "unknown": 
        try:
            age = int(age)
            if age < 0:
                return JsonResponse({"error": "Age cannot be negative!"}, status=400)
        except ValueError:
            return JsonResponse({"error": "Age must be a valid number!"}, status=400)

    # Prepare the response data
    response_data = {
        "message": f"Hello, {name}!",
        "age": age,
        "city": city
    }
    
    # Return a JSON response
    return JsonResponse(response_data)

# URL patterns to map URLs to views
urlpatterns = [
    path('admin/', admin.site.urls),  # Admin panel URL
    path('hello/', hello_world),      # URL for the hello_world function
    path('', include(router.urls)),   # Include all routes generated by the router
]
